language: php

php:
  - 7.0
services:
  - docker

env:
  - PHP_VERSION=5.6 ENABLE_MCRYPT=0 COVERALLS=0
  - PHP_VERSION=5.6 ENABLE_MCRYPT=1 COVERALLS=0
  - PHP_VERSION=7.0 ENABLE_MCRYPT=0 COVERALLS=0
  - PHP_VERSION=7.0 ENABLE_MCRYPT=1 COVERALLS=0
  - PHP_VERSION=7.1 ENABLE_MCRYPT=0 COVERALLS=0
  - PHP_VERSION=7.1 ENABLE_MCRYPT=1 COVERALLS=0
  - PHP_VERSION=7.0 ENABLE_MCRYPT=0 COVERALLS=1

matrix:
  fast_finish: true
  allow_failures:
    - env: PHP_VERSION=5.6 ENABLE_MCRYPT=0 COVERALLS=0
    - env: PHP_VERSION=7.0 ENABLE_MCRYPT=0 COVERALLS=0
    - env: PHP_VERSION=7.0 ENABLE_MCRYPT=0 COVERALLS=1
    - env: PHP_VERSION=7.1 ENABLE_MCRYPT=0 COVERALLS=0

install:
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
